### ISSUE TITLE
OpenGL ES 2.0 Devices

### ISSUE THREAD

**Issue by Rocky5** [gizmo98/gizmo-crt-shader#1]
Would it be possible for you to make this shader OpenGL ES 2.0 compliant?

fwidth is causing the issue. 

I commented out the magnify section and the uv = magnify( part to make it work.

but am not sure what effects that will have on the output. 

I tried fixing it myself but I have never touched shader code in my life 😂

I tried this: https://stackoverflow.com/a/22462714

**Comment by gizmo98** [comment]
Ok. I see the problem. GLSL ES 1.00 does not support fwidth(). OpenGL 2.0‘s GLSL 1.10 has support. Any chance you can use GL >= 2.0?

Magnify is necessary to get sharp evenly looking pixels. It‘s the main part of the uniform-nearest interpolation shader. If you remove function call, pure bilinear filtering will be used. Pixels will look smeared out and so on.

I will take a look if your stackoverflow solution can be used to replicate functionality or if we can use sharp bilinear shader for GLES2.

**Comment by Rocky5** [comment]
Am currently using JELOS on an RG353M (RK3566) and it supports OpenGL ES 2.0 and I assume under. 

When I used the shader the error retroarch would output was “Shader log: 3:201: L0002: No matching function for call to 'fwidth’”

I assumed that meant it didn’t support fwidth.

**Comment by gizmo98** [comment]
I played around a little bit. Had no success with the stackoverflow approach and added sharp bilinear instead. You can find the experimental gles2 solution here:
https://github.com/gizmo98/gizmo-crt-shader/commit/fb9b22066c282015173e6bccafb536a437e5d511

Sharp bilinear output looks a little bit smoother now. 
![slotmask-crt-gles2](https://github.com/gizmo98/gizmo-crt-shader/assets/6412699/c816e3a4-b6eb-46fb-8411-56211715d4c1)

**Comment by Rocky5** [comment]
Thank you 🙏 will test in a bit and get back to you.

**Comment by Rocky5** [comment]
Ok that new one is loading and working. But I don’t know if this is intentional or not but it’s jittering.

I didn’t use the slot mask version so am not sure if that’s how that one is meant to function. 

Also the horizontal scale now goes from right to left instead of left to right.

**Comment by gizmo98** [comment]
Good to know it is working know👍. I have seen some really bad CRTs with vertical jitter. Slotmask has a jitter function which can be commented out. https://github.com/gizmo98/gizmo-crt-shader/blob/gles2/glsl_shaders/crt/shaders/gizmo-slotmask-crt-gles2.glsl#L313

I will modify the normal shader and check scaling tomorrow.

**Comment by Rocky5** [comment]
> Good to know it is working know👍. I have seen some really bad CRTs with vertical jitter. Slotmask has a jitter function which can be commented out. https://github.com/gizmo98/gizmo-crt-shader/blob/gles2/glsl_shaders/crt/shaders/gizmo-slotmask-crt-gles2.glsl#L313
> 
> I will modify the normal shader and check scaling tomorrow.

Thank you 🙏 and the jitter is growing on me 😂

much appreciated and love the shader. Mega drive never looked so good 🙏

**Comment by gizmo98** [comment]
I added a gizmo-crt-gles2 variant. It is not as sharp as the original shader. I also updated the slotmask variant and addeda Jitter enable/disable option. Shrink does not work right with glsl libretro shaders. Same code works fine with slang variant.
https://github.com/gizmo98/gizmo-crt-shader/commit/742346991f0f0f1e164c56653d8fdeed9868fac0

**Comment by Rocky5** [comment]
I’m unable to use the non slot mask version I always get a failed error. 

INFO] [KMS]: New FB: 1280x720 (stride: 5120).
[INFO] [KMS]: New FB: 1280x720 (stride: 5120).
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[ERROR] Failed to load GLSL shader: /tmp/shaders/gizmo-crt/shaders/gizmo-crt-gles2.glsl.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[WARN] [GL]: Failed to set multipass shader. Falling back to stock.

**Comment by gizmo98** [comment]
Looks like gizmo-crt-gles2.glsl is missing. Have you done a manual download or "git pull"? I have downloaded the branch with "git clone https://github.com/gizmo98/gizmo-crt-shader -b gles2" and the shader loads fine.

**Comment by Rocky5** [comment]
> Looks like gizmo-crt-gles2.glsl is missing. Have you done a manual download or "git pull"? I have downloaded the branch with "git clone https://github.com/gizmo98/gizmo-crt-shader -b gles2" and the shader loads fine.

It was yes, but I rebooted and now it’s working. Even thought it was there 🤷‍♂️

I should have rebooted before replying 🙈

**Comment by Rocky5** [comment]
Just want to say thank you for updating this for Gles2 very much appreciated 🙏

**Comment by gizmo98** [comment]
No problem. Have fun!
